import { Configuration, OpenAIApi } from "openai";
// import axios from "axios"
import './App.css'
import { useState } from "react";

const configuration = new Configuration({

  // organization: "org-KpXswoSTFjlOOuA6nrewrYrm",
  apiKey: import.meta.env.VITE_OPENAI_API_KEY,
  
});
const openai = new OpenAIApi(configuration);

function App() {
  
//set the prompt 
const [prompt ,setPrompt]=useState("hey buddy");
const [image,setImage]=useState("");

    //function to generate image 
    async function generateImage(){
      try{
        const response = await openai.createImage({
          prompt: prompt, //taking prompt directly
          n:1,
          size:"1024x1024", 
        })
        const imagelink=response.data.data[0].url;
        console.log(response.data.data[0].url)
        setImage(imagelink)
      }
      catch(e){
        console.log(e.message)
      }
    }
    function handleChange(e){
      
      e.preventDefault();
      setPrompt(e.target.value)
      
    }



  return ( 
    <>
    <div className="app-main">
    <h1>Image Generation using</h1>
    <input type="text" value={prompt} onChange={handleChange} className="app-input"/>
    <button onClick={generateImage} className="app-button">Generate images</button>
    <img src={`${image}`} alt="this is the image generated by image" className="image" />
    </div>
    </>
  )
}

export default App
